// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUg7Fnj7ibGiAcUM38jw83IPdUFjIPwTA',
    appId: '1:610689278779:web:af939544ffdf8ead58cd1e',
    messagingSenderId: '610689278779',
    projectId: 'text-quiz-f0488',
    authDomain: 'text-quiz-f0488.firebaseapp.com',
    storageBucket: 'text-quiz-f0488.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJyxOx_7bVVAiHwX-jqcZmkn9QxEXfVxA',
    appId: '1:610689278779:android:f53487636be4cdfb58cd1e',
    messagingSenderId: '610689278779',
    projectId: 'text-quiz-f0488',
    storageBucket: 'text-quiz-f0488.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6cpIoo5vQ5jf2qlSSSJWd7If9m5gsnn8',
    appId: '1:610689278779:ios:402440dc6d521b5858cd1e',
    messagingSenderId: '610689278779',
    projectId: 'text-quiz-f0488',
    storageBucket: 'text-quiz-f0488.firebasestorage.app',
    iosBundleId: 'com.example.dashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6cpIoo5vQ5jf2qlSSSJWd7If9m5gsnn8',
    appId: '1:610689278779:ios:402440dc6d521b5858cd1e',
    messagingSenderId: '610689278779',
    projectId: 'text-quiz-f0488',
    storageBucket: 'text-quiz-f0488.firebasestorage.app',
    iosBundleId: 'com.example.dashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUg7Fnj7ibGiAcUM38jw83IPdUFjIPwTA',
    appId: '1:610689278779:web:5b607027862eb01458cd1e',
    messagingSenderId: '610689278779',
    projectId: 'text-quiz-f0488',
    authDomain: 'text-quiz-f0488.firebaseapp.com',
    storageBucket: 'text-quiz-f0488.firebasestorage.app',
  );
}
